### ISSUE TITLE
Transfer project to sugarlabs?

### ISSUE THREAD

**Issue by davelab6** [AlanJAS/fischerTX#1]
Unlike https://github.com/AlanJAS/nxt this doesn't seem specific to Sugar... however, I invite you to transfer it to the sugarlabs org to help increase its visibility with the wider public :)

**Comment by AlanJAS** [comment]
This is the repo of a Lego NxT plugin for sugar activity TurtleArt.

**Comment by davelab6** [comment]
Since its related to Sugar, I think more people will find it if its in Sugar Labs :)
